// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package app

import (
	"context"
	"vhome/8v/agconfig"
	"vhome/8v/agent"
	"vhome/8v/llm"
	"vhome/8v/tools"
	"vhome/internal/auth"
	"vhome/internal/config"
	"vhome/internal/http/handler"
	"vhome/internal/http/middleware"
	"vhome/internal/repository"
	"vhome/internal/service"
)

// Injectors from wire.go:

// InitializeAPP is the wire injector. Its body is discarded: `wire` reads the
// signature and the provider list, works out the construction order from the
// parameter and return types, and writes wire_gen.go. Regenerate with
// `go generate ./internal/app` after changing any constructor signature.
func InitializeAPP(ctx context.Context, envFile config.EnvFile) (*APP, func(), error) {
	configConfig, err := config.LoadConfig(envFile)
	if err != nil {
		return nil, nil, err
	}
	appConfig := configConfig.App
	storageConfig := configConfig.Storage
	healthHandler := handler.NewHealthHandler()
	dbConfig := configConfig.DB
	db, cleanup, err := provideDB(ctx, dbConfig)
	if err != nil {
		return nil, nil, err
	}
	repositoryRepository := repository.New(db)
	authConfig := configConfig.Auth
	sessionTTL := provideSessionTTL(authConfig)
	identityService, err := service.NewIdentityService(repositoryRepository, sessionTTL)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	bootstrapHandler := handler.NewBootstrapHandler(identityService, authConfig)
	identityHandler := handler.NewIdentityHandler(identityService, authConfig)
	memberHandler := handler.NewMemberHandler(identityService)
	pantryService := service.NewPantryService(repositoryRepository)
	pantryHandler := handler.NewPantryHandler(pantryService, storageConfig)
	mealService, err := service.NewMealService(repositoryRepository)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	mealHandler := handler.NewMealHandler(mealService, storageConfig)
	expenseService, err := service.NewExpenseService(repositoryRepository)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	expenseHandler := handler.NewExpenseHandler(expenseService)
	memoService, err := service.NewMemoService(repositoryRepository)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	calendarSyncService, err := service.NewCalendarSyncService(repositoryRepository)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	memoHandler := handler.NewMemoHandler(memoService, calendarSyncService)
	securityConfig := configConfig.Security
	encryptionKey := provideEncryptionKey(securityConfig)
	secretBox, err := auth.NewSecretBox(encryptionKey)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	notificationService, err := service.NewNotificationService(repositoryRepository, secretBox)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	notificationHandler := handler.NewNotificationHandler(notificationService)
	dashboardService := service.NewDashboardService(repositoryRepository, pantryService, expenseService, memoService)
	homeHandler := handler.NewHomeHandler(identityService, dashboardService)
	agConfig := agconfig.Load()
	client, err := llm.NewClient(agConfig)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	agentMemoryService, err := service.NewAgentMemoryService(repositoryRepository)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	options := tools.Options{
		Pantry:   pantryService,
		Meal:     mealService,
		Expense:  expenseService,
		Memo:     memoService,
		Identity: identityService,
		Memory:   agentMemoryService,
	}
	registry := tools.NewRegistry(options)
	agentConversationService, err := service.NewAgentConversationService(repositoryRepository)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	agentAgent := agent.New(client, registry, agentConversationService)
	agentHandler := handler.NewAgentHandler(agentAgent, agentConversationService)
	handlers := handler.Handlers{
		Health:       healthHandler,
		Bootstrap:    bootstrapHandler,
		Identity:     identityHandler,
		Member:       memberHandler,
		Pantry:       pantryHandler,
		Meal:         mealHandler,
		Expense:      expenseHandler,
		Memo:         memoHandler,
		Notification: notificationHandler,
		Home:         homeHandler,
		Agent:        agentHandler,
	}
	guards := middleware.NewGuards(identityService, authConfig)
	engine, err := provideEngine(appConfig, storageConfig, handlers, guards)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	workers := Workers{
		Memo:          memoService,
		Notification:  notificationService,
		Calendar:      calendarSyncService,
		Conversations: agentConversationService,
	}
	app := newAPP(configConfig, engine, db, workers)
	return app, func() {
		cleanup()
	}, nil
}
